<%@ Page Title="Edit Item" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="EditItem.aspx.cs" Inherits="EditItem" Theme="Blue" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <asp:hiddenfield id="hiddenField" runat="server" />
    <%--<asp:textbox runat="server" id="hiddenField"></asp:textbox>--%>
    <h1>Edit Item</h1>

    <asp:sqldatasource id="itemDataSource" runat="server" connectionstring="<%$ ConnectionStrings:HomeStorage %>" deletecommand="DELETE FROM [Item] WHERE [ItemId] = @ItemId" selectcommand="SELECT [ItemId], [ItemName], [TypeId], [Tags], [Description], [ContainedBy], [Private], [DateAdded] FROM [Item] WHERE ([ItemId] = @ItemId)" updatecommand="UPDATE [Item] SET [ItemName] = @ItemName, [TypeId] = @TypeId, [Tags] = @Tags, [Description] = @Description, [ContainedBy] = @ContainedBy, [Private] = @Private WHERE [ItemId] = @ItemId">
        <DeleteParameters>
            <asp:Parameter Name="ItemId" Type="Int32" />
        </DeleteParameters>

        <SelectParameters>
            <asp:ControlParameter ControlID="grid" Name="ItemId" PropertyName="SelectedValue" Type="Int32" />
        </SelectParameters>

        <UpdateParameters>
            <asp:Parameter Name="ItemName" Type="String" />
            <asp:Parameter Name="TypeId" Type="Int32" />
            <asp:Parameter Name="Tags" Type="String" />
            <asp:Parameter Name="Description" Type="String" />
            <asp:Parameter Name="ContainedBy" Type="Int32" />
            <asp:Parameter Name="Private" Type="Int32" />
            <asp:Parameter Name="ItemId" Type="Int32" />
        </UpdateParameters>

    </asp:sqldatasource>

    <%--<asp:SqlDataSource ID="itemsDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:HomeStorage %>" SelectCommand="SELECT * FROM [Item] ORDER BY [ItemName]"></asp:SqlDataSource>--%>
    <asp:sqldatasource id="itemsDataSource" runat="server" connectionstring="<%$ ConnectionStrings:HomeStorage %>" selectcommand="SELECT Item.ItemId, [ItemName], [Tags], [ContainedBy] FROM [aspnet_Users] INNER JOIN UserItem  ON aspnet_Users.UserId = UserItem.UserId INNER JOIN Item ON UserItem.ItemId = Item.ItemId WHERE aspnet_Users.UserId = @UserId ORDER BY [ItemName]">
            <SelectParameters>
                <asp:ControlParameter ControlID="hiddenField" Name="UserId" PropertyName="Value" Type="String" />
            </SelectParameters>
    </asp:sqldatasource>

    <asp:sqldatasource id="itemTypesDataSource" runat="server" connectionstring="<%$ ConnectionStrings:HomeStorage %>" selectcommand="SELECT [ItemTypeName], [ItemTypeId] FROM [ItemType]"></asp:sqldatasource>


    <asp:gridview id="grid" runat="server" autogeneratecolumns="False" datasourceid="itemsDataSource" datakeynames="ItemId" allowpaging="False" pagesize="5">
        <Columns>
            <asp:BoundField DataField="ItemId" HeaderText="Item Id" />
            <asp:BoundField DataField="ItemName" HeaderText="Item Name" />
            <asp:BoundField DataField="Tags" HeaderText="Tags" />
            <asp:BoundField DataField="ContainedBy" HeaderText="Container Id" />
            <asp:ButtonField CommandName="Select" Text="Select" />
        </Columns>
    </asp:gridview>

    <br />

    <asp:detailsview id="itemDetails" runat="server" autogeneraterows="False" autogeneratedeletebutton="False" autogenerateeditbutton="True" autogenerateinsertbutton="False" datasourceid="itemDataSource" datakeynames="ItemId" onitemdeleted="itemDetails_ItemDeleted" oniteminserted="itemDetails_ItemInserted" onitemupdated="itemDetails_ItemUpdated">
        <Fields>
            <asp:BoundField DataField="ItemId" HeaderText="Item Id" InsertVisible="False" ReadOnly="True" />

            <asp:BoundField DataField="ItemName" HeaderText="Item Name" ValidateRequestMode="Enabled"
                SortExpression="ItemName" />

            <asp:TemplateField HeaderText="ItemType">
                <EditItemTemplate>
                    <asp:DropDownList ID="didDdl" runat="server"
                        DataSourceID="itemTypesDataSource"
                        DataTextField="ItemTypeName" DataValueField="ItemTypeId"
                        SelectedValue='<%# Bind("TypeId") %>' />
                </EditItemTemplate>

                <InsertItemTemplate>
                    <asp:DropDownList ID="didDdl" runat="server"
                        DataSourceID="itemTypesDataSource"
                        DataTextField="ItemTypeName" DataValueField="ItemTypeId"
                        SelectedValue='<%# Bind("TypeId") %>' />
                </InsertItemTemplate>

                <ItemTemplate>
                    <asp:DropDownList ID="didDdl" runat="server"
                        DataSourceID="itemTypesDataSource"
                        DataTextField="ItemTypeName"
                        DataValueField="ItemTypeId"
                        SelectedValue='<%# Bind("TypeId") %>' Enabled="False" />
                </ItemTemplate>

            </asp:TemplateField>

            <asp:BoundField DataField="Tags" HeaderText="Tags"
                SortExpression="Tags" />

            <asp:BoundField DataField="Description" HeaderText="Description"
                SortExpression="Description" />

            <asp:BoundField DataField="ContainedBy" HeaderText="Container Id"
                SortExpression="ContainedBy" />


            <asp:CheckBoxField DataField="Private" HeaderText="Private" />

            <asp:BoundField DataField="DateAdded" HeaderText="Date Added" InsertVisible="False" ReadOnly="True" />
        </Fields>

        <HeaderTemplate>
            <%#Eval("ItemName") == null ? "Adding New Item" : Eval("ItemName")%>
        </HeaderTemplate>

    </asp:detailsview>


</asp:Content>

