<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Random.aspx.cs" Inherits="Random" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
    </div>
        <asp:HiddenField ID="hiddenField" runat="server" />
        <asp:SqlDataSource ID="itemsDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:HomeStorage %>" SelectCommand="SELECT [ItemId], [ItemName], [Tags], [ContainedBy] FROM [Item] WHERE ([ItemId] = @ItemId) ORDER BY [ItemName]">
            <SelectParameters>
                <asp:ControlParameter ControlID="hiddenField" Name="ItemId" PropertyName="Value" Type="Int32" />
            </SelectParameters>
        </asp:SqlDataSource>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="ItemId" DataSourceID="itemsDataSource">
            <Columns>
                <asp:BoundField DataField="ItemId" HeaderText="ItemId" InsertVisible="False" ReadOnly="True" SortExpression="ItemId" />
                <asp:BoundField DataField="ItemName" HeaderText="ItemName" SortExpression="ItemName" />
                <asp:BoundField DataField="Tags" HeaderText="Tags" SortExpression="Tags" />
                <asp:BoundField DataField="ContainedBy" HeaderText="ContainedBy" SortExpression="ContainedBy" />
            </Columns>
        </asp:GridView>
        <asp:DetailsView ID="DetailsView1" runat="server" Height="50px" Width="125px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateInsertButton="True" AutoGenerateRows="False" DataKeyNames="ItemId" DataSourceID="itemDataSource" OnItemDeleted="DetailsView1_ItemDeleted" OnItemInserted="DetailsView1_ItemInserted" OnItemUpdated="DetailsView1_ItemUpdated">
            <Fields>
                <asp:BoundField DataField="ItemId" HeaderText="Item Id" SortExpression="ItemId" />

                <asp:BoundField DataField="ItemName" HeaderText="ItemName" SortExpression="ItemName" ApplyFormatInEditMode="True" ValidateRequestMode="Enabled" />

                <asp:TemplateField HeaderText="TypeId" SortExpression="TypeId">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("TypeId") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <InsertItemTemplate>
                        <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("TypeId") %>'></asp:TextBox>
                    </InsertItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("TypeId") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:BoundField DataField="Tags" HeaderText="Tags" SortExpression="Tags" />
                <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
                <asp:BoundField DataField="ContainedBy" HeaderText="ContainedBy" SortExpression="ContainedBy" />
                <asp:CheckBoxField DataField="Private" HeaderText="Private" SortExpression="Private" />
                <asp:BoundField DataField="DateAdded" HeaderText="DateAdded" SortExpression="DateAdded" />
                <asp:CommandField ShowEditButton="True" />
            </Fields>
        </asp:DetailsView>
        <asp:SqlDataSource ID="itemDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:HomeStorage %>" DeleteCommand="DELETE FROM [Item] WHERE [ItemId] = @ItemId" InsertCommand="INSERT INTO [Item] ([ItemName], [TypeId], [Tags], [Description], [ContainedBy], [Private], [DateAdded]) VALUES (@ItemName, @TypeId, @Tags, @Description, @ContainedBy, @Private, @DateAdded)" SelectCommand="SELECT * FROM [Item] WHERE ([ItemId] = @ItemId)" UpdateCommand="UPDATE [Item] SET [ItemName] = @ItemName, [TypeId] = @TypeId, [Tags] = @Tags, [Description] = @Description, [ContainedBy] = @ContainedBy, [Private] = @Private, [DateAdded] = @DateAdded WHERE [ItemId] = @ItemId">
            <DeleteParameters>
                <asp:Parameter Name="ItemId" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="ItemName" Type="String" />
                <asp:Parameter Name="TypeId" Type="Int32" />
                <asp:Parameter Name="Tags" Type="String" />
                <asp:Parameter Name="Description" Type="String" />
                <asp:Parameter Name="ContainedBy" Type="Int32" />
                <asp:Parameter Name="Private" Type="Boolean" />
                <asp:Parameter DbType="Date" Name="DateAdded" />
            </InsertParameters>
            <SelectParameters>
                <asp:ControlParameter ControlID="GridView1" Name="ItemId" PropertyName="SelectedValue" Type="Int32" />
            </SelectParameters>
            <UpdateParameters>
                <asp:Parameter Name="ItemName" Type="String" />
                <asp:Parameter Name="TypeId" Type="Int32" />
                <asp:Parameter Name="Tags" Type="String" />
                <asp:Parameter Name="Description" Type="String" />
                <asp:Parameter Name="ContainedBy" Type="Int32" />
                <asp:Parameter Name="Private" Type="Boolean" />
                <asp:Parameter DbType="Date" Name="DateAdded" />
                <asp:Parameter Name="ItemId" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>

        <asp:SqlDataSource ID="itemTypesDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:HomeStorage %>" SelectCommand="SELECT * FROM [ItemType]"></asp:SqlDataSource>
    </form>
</body>
</html>
